// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiciosBiblioteca.Models;

namespace ServiciosBiblioteca.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190715014635_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiciosBiblioteca.Models.tblAutor", b =>
                {
                    b.Property<int?>("idAutor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("fechaNacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("idAutor");

                    b.ToTable("tblAutor");
                });

            modelBuilder.Entity("ServiciosBiblioteca.Models.tblCategoria", b =>
                {
                    b.Property<int?>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("idCategoria");

                    b.ToTable("tblCategoria");
                });

            modelBuilder.Entity("ServiciosBiblioteca.Models.tblLibro", b =>
                {
                    b.Property<int?>("idLibro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idAutor");

                    b.Property<int>("idCategoria");

                    b.Property<int>("isbn");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("idLibro");

                    b.HasIndex("idAutor");

                    b.HasIndex("idCategoria");

                    b.ToTable("tblLibro");
                });

            modelBuilder.Entity("ServiciosBiblioteca.Models.tblLibro", b =>
                {
                    b.HasOne("ServiciosBiblioteca.Models.tblAutor", "tblAutor")
                        .WithMany()
                        .HasForeignKey("idAutor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ServiciosBiblioteca.Models.tblCategoria", "tblCategoria")
                        .WithMany()
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
